apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighttrack.fullname" . }}
  labels:
    {{- include "lighttrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ .Values.secrets.adminKey | quote }}
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
